/*
    ::IRAN
    by :AmirMahdiHassanzadeh
    1400/1/11
    2021/3/31
    myPhone :09211710114
    instagram id:@mahdi_attwi
    telegram id:@Amir_mehdi_attwi
    ::IRAN
*/
#include "sevenSegment.h"

void CLOCK_PORT_EN(void)
{
    #if (SEVENSEGGMENT_WITH_74LS48)
      #if(_GPIOA_CLOCK)
				RCC->APB2ENR |=(1<<2);//enable GPIOA CLOCk
			#endif
			#if(_GPIOB_CLOCK)
						RCC->APB2ENR |=(1<<3);//enable GPIOB CLOCk
					#endif
			#if(_GPIOC_CLOCK)
						RCC->APB2ENR |=(1<<4);//enable GPIOC CLOCk
					#endif
			#if(_GPIOD_CLOCK)
						RCC->APB2ENR |=(1<<5);//enable GPIOD CLOCk
					#endif
			#if(_GPIOE_CLOCK)
						RCC->APB2ENR |=(1<<6);//enable GPIOE CLOCk
					#endif
    #endif
}

void SEVENSEGMENT_INIT(void)
{
	#if (SEVENSEGGMENT_WITH_74LS48)
		//0x3 ==>> cnf == 00 && MODE ==11  speed =50MHZ
	
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_1<=7)
				_SEVEN_SEGMENT_CONTOROL_PORT_1->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_CONTOROL_PIN_1*4));//reset All 
				_SEVEN_SEGMENT_CONTOROL_PORT_1->CRL |=(0x3<<(_SEVEN_SEGMENT_CONTOROL_PIN_1*4));
			#endif
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_1>7)
					_SEVEN_SEGMENT_CONTOROL_PORT_1->CRH &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_CONTOROL_PIN_1-8)*4);
					_SEVEN_SEGMENT_CONTOROL_PORT_1->CRH |=(0x3<<((_SEVEN_SEGMENT_CONTOROL_PIN_1-8)*4));
				#endif
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_2<=7)
				_SEVEN_SEGMENT_CONTOROL_PORT_2->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_CONTOROL_PIN_2*4));//reset All 
				_SEVEN_SEGMENT_CONTOROL_PORT_2->CRL |=(0x3<<(_SEVEN_SEGMENT_CONTOROL_PIN_2*4));
			#endif
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_2>7)
					_SEVEN_SEGMENT_CONTOROL_PORT_1->CRH &=~(uint32_t)(0xF<<((_SEVEN_SEGMENT_CONTOROL_PIN_2-8)*4));//reset All 
					_SEVEN_SEGMENT_CONTOROL_PORT_2->CRH |=(0x3<<((_SEVEN_SEGMENT_CONTOROL_PIN_2-8)*4));
				#endif
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_3<=7)
				_SEVEN_SEGMENT_CONTOROL_PORT_3->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_CONTOROL_PIN_3*4));//reset All 
				_SEVEN_SEGMENT_CONTOROL_PORT_3->CRL |=(0x3<<_SEVEN_SEGMENT_CONTOROL_PIN_3*4);
			#endif
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_3>7)
					_SEVEN_SEGMENT_CONTOROL_PORT_3->CRH &=~(uint32_t)(0xF<<((_SEVEN_SEGMENT_CONTOROL_PIN_3-8)*4));//reset All 
					_SEVEN_SEGMENT_CONTOROL_PORT_3->CRH |=(0x3<<((_SEVEN_SEGMENT_CONTOROL_PIN_3-8)*4));
				#endif
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_4<=7)
			  _SEVEN_SEGMENT_CONTOROL_PORT_4->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_CONTOROL_PIN_4*4));//reset All 
				_SEVEN_SEGMENT_CONTOROL_PORT_4->CRL |=(0x3<<(_SEVEN_SEGMENT_CONTOROL_PIN_4*4));
				#endif
			#if(_SEVEN_SEGMENT_CONTOROL_PIN_4>7)
					_SEVEN_SEGMENT_CONTOROL_PORT_4->CRH &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_CONTOROL_PIN_4-8)*4);//reset All 
					_SEVEN_SEGMENT_CONTOROL_PORT_4->CRH |=(0x3<<((_SEVEN_SEGMENT_CONTOROL_PIN_4-8)*4));
				#endif
	//##################################################################################
			#if(_SEVEN_SEGMENT_74LS48_PIN_1<=7)
			  _SEVEN_SEGMENT_74LS48_PORT_1->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_74LS48_PIN_1*4));//reset All 
				_SEVEN_SEGMENT_74LS48_PORT_1->CRL |=(0x3<<(_SEVEN_SEGMENT_74LS48_PIN_1*4));
			#endif
			#if(_SEVEN_SEGMENT_74LS48_PIN_1>7)
					_SEVEN_SEGMENT_74LS48_PORT_1->CRH &=~(uint32_t)(0xF<<((_SEVEN_SEGMENT_74LS48_PIN_1-8)*4));//reset All 
					_SEVEN_SEGMENT_74LS48_PORT_1->CRH |=(0x3<<(_SEVEN_SEGMENT_74LS48_PIN_1-8)*4);
				#endif
				#if(_SEVEN_SEGMENT_74LS48_PIN_2<=7)
				_SEVEN_SEGMENT_74LS48_PORT_2->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_74LS48_PIN_2*4));//reset All 
				_SEVEN_SEGMENT_74LS48_PORT_2->CRL |=(0x3<<(_SEVEN_SEGMENT_74LS48_PIN_2*4));
			#endif
			#if(_SEVEN_SEGMENT_74LS48_PIN_2>7)
					_SEVEN_SEGMENT_74LS48_PORT_2->CRH &=~(uint32_t)(0xF<<((_SEVEN_SEGMENT_74LS48_PIN_2-8)*4));//reset All 
					_SEVEN_SEGMENT_74LS48_PORT_2->CRH |=(0x3<<((_SEVEN_SEGMENT_74LS48_PIN_2-8)*4));
				#endif
				#if(_SEVEN_SEGMENT_74LS48_PIN_4<=7)
				_SEVEN_SEGMENT_74LS48_PORT_4->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_74LS48_PIN_4*4));//reset All 
				_SEVEN_SEGMENT_74LS48_PORT_4->CRL |=(0x3<<(_SEVEN_SEGMENT_74LS48_PIN_4*4));
			#endif
			#if(_SEVEN_SEGMENT_74LS48_PIN_4>7)
					_SEVEN_SEGMENT_74LS48_PORT_4->CRH &=~(uint32_t)(0xF<<((_SEVEN_SEGMENT_74LS48_PIN_4-8)*4));//reset All 
					_SEVEN_SEGMENT_74LS48_PORT_4->CRH |=(0x3<<((_SEVEN_SEGMENT_74LS48_PIN_4-8)*4));
				#endif
			#if(_SEVEN_SEGMENT_74LS48_PIN_8<=7)
				_SEVEN_SEGMENT_74LS48_PORT_8->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_74LS48_PIN_8*4));//reset All 
				_SEVEN_SEGMENT_74LS48_PORT_8->CRL |=(0x3<<(_SEVEN_SEGMENT_74LS48_PIN_8*4));
			#endif
			#if(_SEVEN_SEGMENT_74LS48_PIN_8>7)
					_SEVEN_SEGMENT_74LS48_PORT_8->CRH &=~(uint32_t)(0xF<<((_SEVEN_SEGMENT_74LS48_PIN_8-8)*4));//reset All 
					_SEVEN_SEGMENT_74LS48_PORT_8->CRH |=(0x3<<((_SEVEN_SEGMENT_74LS48_PIN_8-8)*4));
				#endif
			
//########################################################################################

		#if(_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN<=7)
				_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->CRL &=~(uint32_t)(0xF<<(_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN*4));//reset All 
				_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->CRL |=(0x3<<_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN*4);
			#endif
			#if(_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN>7)
					_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->CRH &=~(uint32_t)(0xF <<((_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN-8)*4));//reset All 	
					_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->CRH |=(0x3<<((_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN-8)*4));
				#endif

		#endif
	
	
	
	
}

char BCD_NUMBER_MOVE_TO_74LS48(uint8_t num)
{
	uint8_t A=0,B=0,C=0,D=0;
		A=num&0x01;
		B=(num&0x02)>>1;
		C=(num&0x04)>>2;
		D=(num&0x08)>>3;
	if(num >= 10)
	{
			return 0;
	}
	else
	{
		(A)?(_SEVEN_SEGMENT_74LS48_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_74LS48_PIN_1)):(_SEVEN_SEGMENT_74LS48_PORT_1->BSRR |= (1<<(_SEVEN_SEGMENT_74LS48_PIN_1+16)));
		(B)?(_SEVEN_SEGMENT_74LS48_PORT_2->BSRR |= (1<<_SEVEN_SEGMENT_74LS48_PIN_2)):(_SEVEN_SEGMENT_74LS48_PORT_2->BSRR |= (1<<(_SEVEN_SEGMENT_74LS48_PIN_2+16)));
		(C)?(_SEVEN_SEGMENT_74LS48_PORT_4->BSRR |= (1<<_SEVEN_SEGMENT_74LS48_PIN_4)):(_SEVEN_SEGMENT_74LS48_PORT_4->BSRR |= (1<<(_SEVEN_SEGMENT_74LS48_PIN_4+16)));
		(D)?(_SEVEN_SEGMENT_74LS48_PORT_8->BSRR |= (1<<_SEVEN_SEGMENT_74LS48_PIN_8)):(_SEVEN_SEGMENT_74LS48_PORT_8->BSRR |= (1<<(_SEVEN_SEGMENT_74LS48_PIN_8+16)));
		
			return 1;
	}
}

void SHOW_VALUE_IN_SEVENSEGMENT(uint16_t num,uint16_t *selector)
{
	int yekan,dahgan,sadgan,hezargan;
	yekan=num%10;
	num/=10;
	dahgan=num%10;
	num/=10;
	sadgan=num%10;
	hezargan=num/10;
	
	switch(*selector)
	{
		case 0:
			BCD_NUMBER_MOVE_TO_74LS48((uint8_t)hezargan);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BRR  |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
		*selector=1;
		break;
		case 1:
			BCD_NUMBER_MOVE_TO_74LS48((uint8_t)sadgan);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
		*selector=2;
		break;
		case 2:
		BCD_NUMBER_MOVE_TO_74LS48((uint8_t)dahgan);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
		*selector=3;
		break;
		case 3:
			BCD_NUMBER_MOVE_TO_74LS48((uint8_t)yekan);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		*selector=0;
		break;
	
	}
	
	
}
void SHOW_FLOAT_VALUE_IN_SEVENSEGMENT(float Floatnum,uint16_t *selector)
{
	int num =(int )Floatnum;
	float Fnum=((Floatnum-(float)num)+0.01)*10;
	int yekan,dahgan,sadgan;
	yekan=num%10;
	num/=10;
	dahgan=num%10;
	num/=10;
	sadgan=num%10;
	
	
	switch(*selector)
	{
		case 0:
			BCD_NUMBER_MOVE_TO_74LS48((uint8_t)Fnum);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->BRR|=(1<<_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN);
		*selector=1;
		break;
		case 1:
			BCD_NUMBER_MOVE_TO_74LS48((uint8_t)sadgan);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
		_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->BRR|=(1<<_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN);
		*selector=2;
		break;
		case 2:
		BCD_NUMBER_MOVE_TO_74LS48((uint8_t)dahgan);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
	_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->BRR|=(1<<_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN);
	*selector=3;
		break;
		case 3:
			BCD_NUMBER_MOVE_TO_74LS48((uint8_t)yekan);
		_SEVEN_SEGMENT_CONTOROL_PORT_4->BRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_3);
		_SEVEN_SEGMENT_CONTOROL_PORT_2->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_2);
		_SEVEN_SEGMENT_CONTOROL_PORT_3->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_4);
		_SEVEN_SEGMENT_CONTOROL_PORT_1->BSRR |= (1<<_SEVEN_SEGMENT_CONTOROL_PIN_1);
		_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PORT->BSRR|=(1<<_SEVEN_SEGMENT_DOT_POINT_CONTOROL_PIN);
		*selector=0;
		break;
	
	}
	
	
}


